CREATE TABLE CLIENTES_BANCA(
	NoCuenta varchar(5),
	Nombre varchar(30),
	Saldo numeric(10,2),
	CONSTRAINT pk_cb PRIMARY KEY (NoCuenta)
)

CREATE TABLE Tipos_Movimiento(
	ClaveM varchar(2),
	Descripcion varchar(30),
	CONSTRAINT pk_tm PRIMARY KEY (ClaveM)
)

CREATE TABLE Realizan(
	NoCuenta varchar(5),
	ClaveM varchar(2),
	Fecha datetime,
	Monto numeric(10,2),
	CONSTRAINT pk_r PRIMARY KEY (NoCuenta, ClaveM, Fecha),
	CONSTRAINT fk_cuenta FOREIGN KEY (NoCuenta) REFERENCES CLIENTES_BANCA(NoCuenta),
	CONSTRAINT fk_clave FOREIGN KEY (claveM) REFERENCES Tipos_Movimiento(ClaveM)
)

BEGIN TRANSACTION PRUEBA1 
INSERT INTO CLIENTES_BANCA VALUES('001', 'Manuel Rios Maldonado', 9000); 
INSERT INTO CLIENTES_BANCA VALUES('002', 'Pablo Perez Ortiz', 5000); 
INSERT INTO CLIENTES_BANCA VALUES('003', 'Luis Flores Alvarado', 8000); 
COMMIT TRANSACTION PRUEBA1

SELECT * FROM CLIENTES_BANCA

BEGIN TRANSACTION PRUEBA2 
INSERT INTO CLIENTES_BANCA VALUES('004','Ricardo Rios Maldonado',19000); 
INSERT INTO CLIENTES_BANCA VALUES('005','Pablo Ortiz Arana',15000); 
INSERT INTO CLIENTES_BANCA VALUES('006','Luis Manuel Alvarado',18000);

SELECT * FROM CLIENTES_BANCA

ROLLBACK TRANSACTION PRUEBA2 

BEGIN TRANSACTION PRUEBA3 
INSERT INTO TIPOS_MOVIMIENTO VALUES('A','Retiro Cajero Automatico'); 
INSERT INTO TIPOS_MOVIMIENTO VALUES('B','Deposito Ventanilla'); 
COMMIT TRANSACTION PRUEBA3 

BEGIN TRANSACTION PRUEBA4 
INSERT INTO Realizan VALUES('001','A',GETDATE(),500); 
UPDATE CLIENTES_BANCA SET SALDO = SALDO -500 
WHERE NoCuenta='001' 
COMMIT TRANSACTION PRUEBA4 

SELECT * FROM CLIENTES_BANCA

SELECT * FROM Realizan

BEGIN TRANSACTION PRUEBA5 
INSERT INTO CLIENTES_BANCA VALUES('005','Rosa Ruiz Maldonado',9000);
INSERT INTO CLIENTES_BANCA VALUES('006','Luis Camino Ortiz',5000); 
INSERT INTO CLIENTES_BANCA VALUES('001','Oscar Perez Alvarado',8000); 


IF @@ERROR = 0 
COMMIT TRANSACTION PRUEBA5 
ELSE 
BEGIN 
PRINT 'A transaction needs to be rolled back' 
ROLLBACK TRANSACTION PRUEBA5 
END 

IF EXISTS (SELECT name FROM sysobjects
	WHERE name = 'REGISTRAR_RETIRO_CAJERO' AND type = 'P')
	DROP PROCEDURE REGISTRAR_RETIRO_CAJERO
GO

CREATE PROCEDURE REGISTRAR_RETIRO_CAJERO
	@uNoCuenta varchar(5),
	@uMonto numeric(10,2)
AS
	BEGIN TRANSACTION
	INSERT INTO Realizan VALUES(@uNoCuenta,'A',GETDATE(),@uMonto); 
	UPDATE CLIENTES_BANCA SET SALDO = SALDO - @uMonto
	WHERE NoCuenta=@uNoCuenta 
	IF @@ERROR = 0
	COMMIT TRANSACTION
	ELSE 
	BEGIN
	PRINT 'Ha habido un error, revise los datos ingresados'
	ROLLBACK TRANSACTION
	END
GO

IF EXISTS (SELECT name FROM sysobjects
	WHERE name = 'REGISTRAR_DEPOSITO_VENTANILLA ' AND type = 'P')
	DROP PROCEDURE REGISTRAR_DEPOSITO_VENTANILLA 
GO

CREATE PROCEDURE REGISTRAR_DEPOSITO_VENTANILLA 
	@uNoCuenta varchar(5),
	@uMonto numeric(10,2)
AS
	BEGIN TRANSACTION
	INSERT INTO Realizan VALUES(@uNoCuenta,'B',GETDATE(),@uMonto); 
	UPDATE CLIENTES_BANCA SET SALDO = SALDO + @uMonto
	WHERE NoCuenta=@uNoCuenta 
	IF @@ERROR = 0
	COMMIT TRANSACTION
	ELSE 
	BEGIN
	PRINT 'Ha habido un error, revise los datos ingresados'
	ROLLBACK TRANSACTION
	END
GO

EXECUTE REGISTRAR_RETIRO_CAJERO '001', 1000
EXECUTE REGISTRAR_RETIRO_CAJERO '100', 1000

EXECUTE REGISTRAR_DEPOSITO_VENTANILLA '001', 1000
EXECUTE REGISTRAR_DEPOSITO_VENTANILLA '100', 1000

SELECT * FROM Realizan
SELECT * FROM CLIENTES_BANCA

